# Generated by Django 2.1.5 on 2019-02-16 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=15)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Address_Info',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custName', models.CharField(max_length=15)),
                ('custAge', models.IntegerField()),
                ('custBalance', models.IntegerField()),
            ],
            options={
                'db_table': 'Customer_Info',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=15)),
                ('productPrice', models.IntegerField()),
                ('productQty', models.IntegerField()),
                ('productCat', models.CharField(max_length=300)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='productapp.Customer')),
            ],
            options={
                'db_table': 'Product_Info',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorName', models.CharField(max_length=15)),
                ('vendorBalance', models.IntegerField()),
                ('address_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='productapp.Address')),
                ('products', models.ManyToManyField(related_name='vendors', to='productapp.Product')),
            ],
            options={
                'db_table': 'Vendor_Info',
            },
        ),
    ]
